-- Chatbox

-- Sotre sounds
local chatsounds = {}

-- Add, stolen from noxiousnet :O
function AddChatSound( trigger, ... )
	local args = { ... }
	if not ( trigger ) then return end
	if not ( args ) then return end
	
	for k, v in pairs( args ) do
		if ( type( args[k] ) == "boolean" ) then args[k] = nil end
	end

	table.insert(chatsounds, { ["trigger"] = trigger, ["sound"] = args } )
end

-- Huge list
AddChatSound("enough of your mumbo jumbo", "vo/npc/male01/vanswer01.wav", true)
AddChatSound("bullshit", "vo/npc/male01/question26.wav")
AddChatSound("yay", "vo/npc/Barney/ba_yell.wav")
AddChatSound("shit", "vo/npc/Barney/ba_ohshit03.wav")
AddChatSound("hax", "vo/npc/male01/hacks01.wav", true)
AddChatSound("hacks", "vo/npc/male01/hacks02.wav", true)
AddChatSound("h4x", "vo/npc/male01/thehacks01.wav", true)
AddChatSound("h4cks", "vo/npc/male01/thehacks02.wav", true)
AddChatSound("okay", "vo/npc/male01/ok01.wav", "vo/npc/male01/ok02.wav")
AddChatSound("derka", "vo/npc/vortigaunt/vortigese12.wav", "vo/npc/vortigaunt/vortigese11.wav", true)
AddChatSound("noes", "vo/npc/Alyx/ohno_startle01.wav", true)
AddChatSound("get down", "vo/npc/Barney/ba_getdown.wav", "vo/npc/male01/getdown02.wav")
AddChatSound("gtfo", "vo/npc/male01/gethellout.wav")
AddChatSound("gtho", "vo/npc/male01/gethellout.wav")
AddChatSound("yeah", "vo/npc/male01/yeah02.wav")
AddChatSound("rofl", "vo/Citadel/br_laugh01.wav")
AddChatSound("lmao", "vo/Citadel/br_laugh01.wav")
AddChatSound("run", "vo/npc/male01/strider_run.wav")
AddChatSound("run for your life", "vo/npc/male01/runforyourlife01.wav", "vo/npc/male01/runforyourlife02.wav", "vo/npc/male01/runforyourlife03.wav")
AddChatSound("fantastic", "vo/npc/male01/fantastic01.wav", "vo/npc/male01/fantastic02.wav")
AddChatSound("headcrabs", "vo/npc/male01/headcrabs01.wav", "vo/npc/male01/headcrabs02.wav")
AddChatSound("headhumpers", "vo/npc/Barney/ba_headhumpers.wav", true)
AddChatSound("hello", "vo/coast/odessa/nlo_cub_hello.wav")
AddChatSound("eek", "ambient/voices/f_scream1.wav", true)
AddChatSound("uh oh", "vo/npc/male01/uhoh.wav")
AddChatSound("sodomy!", "vo/ravenholm/madlaugh01.wav", "vo/ravenholm/madlaugh02.wav", "vo/ravenholm/madlaugh03.wav", "vo/ravenholm/madlaugh04.wav", true)
AddChatSound("oops", "vo/npc/male01/whoops01.wav", true)
AddChatSound("shut up", "vo/npc/male01/answer17.wav")
AddChatSound("shutup", "vo/npc/male01/answer17.wav")
AddChatSound("right on", "vo/npc/male01/answer32.wav", true)
AddChatSound("freeman", "vo/npc/male01/gordead_ques03a.wav", true)
AddChatSound("help", "vo/npc/male01/help01.wav")
AddChatSound("haxz", "vo/npc/male01/herecomehacks01.wav", true)
AddChatSound("hi", "vo/npc/male01/hi01.wav", "vo/npc/male01/hi02.wav")
AddChatSound("let's go", "vo/npc/male01/letsgo01.wav", "vo/npc/male01/letsgo02.wav")
AddChatSound("lets go", "vo/npc/male01/letsgo01.wav", "vo/npc/male01/letsgo02.wav")
AddChatSound("moan", "vo/npc/male01/moan01.wav", "vo/npc/male01/moan02.wav", "vo/npc/male01/moan03.wav", "vo/npc/male01/moan04.wav", "vo/npc/male01/moan05.wav", true)
AddChatSound("nice", "vo/npc/male01/nice.wav")
AddChatSound("noo", "vo/npc/Barney/ba_no01.wav", "vo/npc/Barney/ba_no02.wav", true)
AddChatSound("nooo", "vo/npc/male01/no02.wav", true)
AddChatSound("oh no", "vo/npc/male01/ohno.wav")
AddChatSound("joygasm", "vo/npc/female01/pain06.wav", true)
AddChatSound("zombies", "vo/npc/male01/zombies01.wav", "vo/npc/male01/zombies02.wav")
AddChatSound("da man", "bot/whos_the_man.wav", true)
AddChatSound("my house", "bot/this_is_my_house.wav", true)
AddChatSound("party", "bot/its_a_party.wav", true)
AddChatSound("watch out", "vo/npc/male01/watchout.wav")
AddChatSound("excuse me", "vo/npc/male01/excuseme01.wav", "vo/npc/male01/excuseme02.wav")
AddChatSound("you sure?", "vo/npc/male01/answer37.wav")
AddChatSound("groan", "vo/npc/male01/moan04.wav", true)
AddChatSound("gasp", "vo/npc/male01/startle01.wav", "vo/npc/male01/startle02.wav", true)
AddChatSound("sorry", "vo/npc/male01/sorry01.wav", "vo/npc/male01/sorry02.wav", "vo/npc/male01/sorry03.wav")
AddChatSound("welcome to city 17", "vo/Breencast/br_welcome01.wav", "vo/Breencast/br_welcome06.wav", true)
AddChatSound("it's safer here", "vo/Breencast/br_welcome07.wav", true)
AddChatSound("i'm talking to you", "vo/Breencast/br_tofreeman02.wav", true)
AddChatSound("serve mankind", "vo/Breencast/br_tofreeman12.wav", true)
AddChatSound("get going", "vo/canals/shanty_go_nag03.wav")
AddChatSound("go on out", "vo/canals/gunboat_goonout.wav", true)
AddChatSound("get outta here", "vo/canals/shanty_go_nag01.wav", "vo/canals/boxcar_go_nag03.wav")
AddChatSound("go on", "vo/canals/shanty_go_nag02.wav")
AddChatSound("hey", "vo/canals/shanty_hey.wav")
AddChatSound("get in here hurry", "vo/canals/matt_getin.wav", true)
AddChatSound("hit the road jack", "vo/canals/boxcar_go_nag04.wav", true)
AddChatSound("no", "vo/Citadel/eli_notobreen.wav")
AddChatSound("no!", "vo/Citadel/br_failing11.wav", true)
AddChatSound("never", "vo/Citadel/eli_nonever.wav")
AddChatSound("you fool", "vo/Citadel/br_youfool.wav", true)
AddChatSound("good god", "vo/Citadel/eli_goodgod.wav")
AddChatSound("cheer", "vo/coast/odessa/male01/nlo_cheer01.wav", "vo/coast/odessa/male01/nlo_cheer02.wav", "vo/coast/odessa/male01/nlo_cheer03.wav", "vo/coast/odessa/male01/nlo_cheer04.wav", true)
AddChatSound("drive safely", "vo/coast/odessa/male01/nlo_citizen_drivesafe.wav", true)
AddChatSound("whoops", "vo/k_lab/ba_whoops.wav", true)
AddChatSound("gee thanks", "vo/k_lab/ba_geethanks.wav")
AddChatSound("what the hell", "vo/k_lab/ba_whatthehell.wav")
AddChatSound("it's your pet the freakin headhumper", "vo/k_lab/ba_headhumper01.wav", true)
AddChatSound("i'll stay here", "vo/npc/male01/illstayhere01.wav", "vo/npc/male01/imstickinghere01.wav")
AddChatSound("up there", "vo/npc/male01/upthere01.wav", "vo/npc/male01/upthere02.wav")
AddChatSound("he's dead", "vo/npc/male01/gordead_ques01.wav", "vo/npc/male01/gordead_ques07.wav", true)
AddChatSound("lead the way", "vo/npc/male01/leadtheway02.wav", "vo/npc/male01/leadtheway01.wav", true)
AddChatSound("we're done for", "vo/npc/male01/gordead_ans14.wav", true)
AddChatSound("over there", "vo/npc/male01/overthere01.wav", "vo/npc/male01/overthere02.wav")
AddChatSound("ok i'm ready", "vo/npc/male01/okimready01.wav", "vo/npc/male01/okimready02.wav", "vo/npc/male01/okimready03.wav")
AddChatSound("i'm with you", "vo/npc/male01/answer13.wav", true)
AddChatSound("hey over here", "vo/npc/male01/overhere01.wav", true)
AddChatSound("behind you", "vo/npc/male01/behindyou01.wav", "vo/npc/male01/behindyou02.wav")
AddChatSound("follow me", "vo/npc/male01/squad_away03.wav")
AddChatSound("pardon me", "vo/npc/male01/pardonme01.wav", "vo/npc/male01/pardonme02.wav")
AddChatSound("got one", "vo/npc/male01/gotone01.wav", "vo/npc/male01/gotone02.wav")
AddChatSound("finally", "vo/npc/male01/finally.wav")
AddChatSound("wait for me", "vo/npc/male01/squad_reinforce_single04.wav")
AddChatSound("i'm hurt", "vo/npc/male01/imhurt01.wav", true)
AddChatSound("take cover", "vo/npc/male01/takecover02.wav")
AddChatSound("it's a manhack", "vo/npc/male01/itsamanhack02.wav", true)
AddChatSound("incoming", "vo/npc/male01/incoming02.wav")
AddChatSound("ready when you are", "vo/npc/male01/readywhenyouare01.wav", "vo/npc/male01/readywhenyouare02.wav", true)
AddChatSound("don't forget hawaii", "vo/npc/male01/answer34.wav", true)
AddChatSound("that's enough outta you", "vo/npc/male01/answer39.wav", true)
AddChatSound("wait for us", "vo/npc/male01/squad_reinforce_group04.wav")
AddChatSound("now what?", "vo/npc/male01/gordead_ans01.wav")
AddChatSound("we trusted you", "vo/npc/male01/wetrustedyou01.wav", "vo/npc/male01/wetrustedyou02.wav", true)
AddChatSound("god i'm hungry", "vo/npc/male01/question28.wav", true)
AddChatSound("i'm ganna be sick", "vo/npc/male01/gordead_ans19.wav", true)
AddChatSound("you're talking to yourself again", "vo/npc/male01/answer09.wav", true)
AddChatSound("come on everybody", "vo/npc/male01/squad_follow02.wav", true)
AddChatSound("watch what you're doing", "vo/npc/male01/watchwhat.wav", true)
AddChatSound("your mind is in the gutter", "vo/npc/male01/answer20.wav", true)
AddChatSound("here they come!", "vo/npc/male01/heretheycome01.wav", true)
AddChatSound("same here", "vo/npc/male01/answer07.wav")
AddChatSound("i wouldn't say that too loud", "vo/npc/male01/answer10.wav", true)
AddChatSound("i'll put it on your tombstone", "vo/npc/male01/answer11.wav", true)
AddChatSound("have you ever had an original thought?", "vo/npc/male01/answer16.wav", true)
AddChatSound("let's concentrate on the task at hand", "vo/npc/male01/answer18.wav", true)
AddChatSound("keep your mind on your work", "vo/npc/male01/answer19.wav", true)
AddChatSound("you never know", "vo/npc/male01/answer22.wav", true)
AddChatSound("you never can tell", "vo/npc/male01/answer23.wav", true)
AddChatSound("why are you telling me?", "vo/npc/male01/answer24.wav", true)
AddChatSound("how about that", "vo/npc/male01/answer25.wav", true)
AddChatSound("want a bet?", "vo/npc/male01/answer27.wav")
AddChatSound("what am i supposed to do about it?", "vo/npc/male01/answer29.wav")
AddChatSound("you talking to me?", "vo/npc/male01/answer30.wav")
AddChatSound("leave it alone", "vo/npc/male01/answer38.wav", true)
AddChatSound("can't you see i'm busy?", "vo/npc/male01/busy02.wav", true)
AddChatSound("look out below", "vo/npc/male01/cit_dropper04.wav", true)
AddChatSound("shouldn't we be doing something?", "vo/npc/male01/doingsomething.wav", true)
AddChatSound("let's even the odds a little", "vo/npc/male01/evenodds.wav", true)
AddChatSound("oh god", "vo/npc/male01/gordead_ans04.wav")
AddChatSound("should we bury him here?", "vo/npc/male01/gordead_ans08.wav", true)
AddChatSound("what's the use?", "vo/npc/male01/gordead_ans11.wav", true)
AddChatSound("what's the point?", "vo/npc/male01/gordead_ans12.wav", true)
AddChatSound("this is bad", "vo/npc/male01/gordead_ques10.wav", true)
AddChatSound("hold down this spot", "vo/npc/male01/holddownspot01.wav", "vo/npc/male01/holddownspot02.wav", true)
AddChatSound("i'm hurt", "vo/npc/male01/imhurt01.wav", "vo/npc/male01/imhurt02.wav", true)
AddChatSound("im hurt", "vo/npc/male01/imhurt01.wav", "vo/npc/male01/imhurt02.wav", true)
AddChatSound("sometimes i dream about cheese", "vo/npc/male01/question06.wav", true)
AddChatSound("i can't remember the last time i had a shower", "vo/npc/male01/question19.wav", true)
AddChatSound("watch what you're doing", "vo/npc/male01/watchwhat.wav", true)
AddChatSound("you got it", "vo/npc/male01/yougotit02.wav")
AddChatSound("we thought you were here to help", "vo/npc/male01/heretohelp01.wav", "vo/npc/male01/heretohelp02.wav", true)
AddChatSound("hey doc", "vo/npc/male01/heydoc01.wav", "vo/npc/male01/heydoc02.wav", true)
AddChatSound("hit in the gut", "vo/npc/male01/hitingut01.wav", "vo/npc/male01/hitingut02.wav", true)
AddChatSound("like that?", "vo/npc/male01/likethat.wav", true)
AddChatSound("my leg", "vo/npc/male01/myleg01.wav", "vo/npc/male01/myleg02.wav", true)
AddChatSound("my gut", "vo/npc/male01/mygut02.wav", true)
AddChatSound("my arm", "vo/npc/male01/myarm01.wav", "vo/npc/male01/myarm02.wav", true)
AddChatSound("no no", "vo/npc/male01/no01.wav")
AddChatSound("you're not the man i thought you were", "vo/npc/male01/notthemanithought01.wav", true)
AddChatSound("one for me and one for me", "vo/npc/male01/oneforme.wav", true)
AddChatSound("let me get out of your way", "vo/npc/male01/outofyourway02.wav", true)
AddChatSound("i don't think this war is ever going to end", "vo/npc/male01/question01.wav", true)
AddChatSound("to think all i used to want to do is sell insurance", "vo/npc/male01/question02.wav", true)
AddChatSound("i don't dream anymore", "vo/npc/male01/question03.wav", true)
AddChatSound("when this is all over ah who am i kidding", "vo/npc/male01/question04.wav", true)
AddChatSound("woah deja vu", "vo/npc/male01/question05.wav", true)
AddChatSound("you smell that? it's freedom", "vo/npc/male01/question07.wav", true)
AddChatSound("if i ever get my hands on dr. breen", "vo/npc/male01/question08.wav", true)
AddChatSound("i could eat a horse hooves and all", "vo/npc/male01/question09.wav", true)
AddChatSound("i can't believe this day has finally come", "vo/npc/male01/question10.wav", true)
AddChatSound("i'm pretty sure this isn't part of the plan", "vo/npc/male01/question11.wav", true)
AddChatSound("looks to me like things are getting worse not better", "vo/npc/male01/question12.wav", true)
AddChatSound("if i could live my life over again", "vo/npc/male01/question13.wav", true)
AddChatSound("i'm not even gonna tell you what that reminds me of", "vo/npc/male01/question14.wav", true)
AddChatSound("they're never gonna make a stalker outta me", "vo/npc/male01/question15.wav", true)
AddChatSound("finally change is in the air", "vo/npc/male01/question16.wav", true)
AddChatSound("you feel it? i feel it", "vo/npc/male01/question17.wav", true)
AddChatSound("i don't feel anything anymore", "vo/npc/male01/question18.wav", true)
AddChatSound("some day this will all be a bad memory", "vo/npc/male01/question20.wav", true)
AddChatSound("i'm not a betting man but the odds are not good", "vo/npc/male01/question21.wav", true)
AddChatSound("doesn't anyone care what i think?", "vo/npc/male01/question22.wav", true)
AddChatSound("i can't get this tune outta my head", "vo/npc/male01/question23.wav", true)
AddChatSound("i just knew it was gonna be one of those days", "vo/npc/male01/question25.wav", true)
AddChatSound("i think i ate something bad", "vo/npc/male01/question27.wav", true)
AddChatSound("when this is all over i'm gonna mate", "vo/npc/male01/question29.wav", true)
AddChatSound("i'm glad there's no kids around to see this", "vo/npc/male01/question30.wav", true)
AddChatSound("scanners", "vo/npc/male01/scanners01.wav", true)
AddChatSound("whatever you say", "vo/npc/male01/squad_affirm03.wav")
AddChatSound("ok i'm going", "vo/npc/male01/squad_affirm04.wav", true)
AddChatSound("here it goes", "vo/npc/male01/squad_affirm05.wav", true)
AddChatSound("here goes nothing", "vo/npc/male01/squad_affirm06.wav", true)
AddChatSound("here we come", "vo/npc/male01/squad_approach02.wav", true)
AddChatSound("on our way", "vo/npc/male01/squad_approach03.wav", true)
AddChatSound("coming", "vo/npc/male01/squad_approach04.wav")
AddChatSound("this way gang", "vo/npc/male01/squad_away01.wav", true)
AddChatSound("over here", "vo/npc/male01/squad_away02.wav")
AddChatSound("let's get moving", "npc/male01/squad_follow03.wav")
AddChatSound("gordon freeman, you're here", "vo/npc/male01/squad_greet01.wav", true)
AddChatSound("stop it freeman", "vo/npc/male01/stopitfm.wav", true)
AddChatSound("strider", "vo/npc/male01/strider.wav", true)
AddChatSound("this'll do nicely", "vo/npc/male01/thislldonicely01.wav", true)
AddChatSound("damn vorts", "vo/npc/male01/vanswer02.wav", true)
AddChatSound("i'm not sure how to take that", "vo/npc/male01/vanswer03.wav", true)
AddChatSound("should i take that personally?", "vo/npc/male01/vanswer04.wav", true)
AddChatSound("speak english", "vo/npc/male01/vanswer05.wav", true)
AddChatSound("you got that from me", "vo/npc/male01/vanswer06.wav", true)
AddChatSound("that's why we put up with you", "vo/npc/male01/vanswer07.wav", true)
AddChatSound("couldn't have put it better myself", "vo/npc/male01/vanswer08.wav", true)
AddChatSound("that almost made sense", "vo/npc/male01/vanswer09.wav", true)
AddChatSound("something must be wrong with me i almost understood that", "vo/npc/male01/vanswer10.wav", true)
AddChatSound("i guess i'm getting used to you vorts", "vo/npc/male01/vanswer11.wav", true)
AddChatSound("none of your vort philosophy", "vo/npc/male01/vanswer12.wav", true)
AddChatSound("stop you're killing me", "vo/npc/male01/vanswer13.wav", true)
AddChatSound("what did i do to deserve this?", "vo/npc/male01/vanswer14.wav", true)
AddChatSound("stop looking at me like that", "vo/npc/male01/vquestion01.wav", true)
AddChatSound("some things i just never get used to", "vo/npc/male01/vquestion02.wav", true)
AddChatSound("i don't know how you things survived as long as you have", "vo/npc/male01/vquestion03.wav", true)
AddChatSound("sometimes i wonder how i ended up with you", "vo/npc/male01/vquestion04.wav", true)
AddChatSound("you're alright vorty", "vo/npc/male01/vquestion05.wav", true)
AddChatSound("you vorts aren't half bad", "vo/npc/male01/vquestion06.wav", true)
AddChatSound("if anyone ever told me i'd be pals with a vortigaunt", "vo/npc/male01/vquestion07.wav", true)
AddChatSound("you waiting for somebody?", "vo/npc/male01/waitingsomebody.wav", true)
AddChatSound("woops", "vo/npc/male01/whoops01.wav", true)
AddChatSound("you'd better reload", "vo/npc/male01/youdbetterreload01.wav", true)
AddChatSound("bring it on", "vo/npc/Barney/ba_bringiton.wav", true)
AddChatSound("damnit", "vo/npc/Barney/ba_damnit.wav")
AddChatSound("i don't like the looks of this", "vo/npc/Barney/ba_danger02.wav", true)
AddChatSound("down you go", "vo/npc/Barney/ba_downyougo.wav", true)
AddChatSound("duck", "vo/npc/Barney/ba_duck.wav")
AddChatSound("come on", "vo/npc/Barney/ba_followme02.wav")
AddChatSound("get away from there", "vo/npc/Barney/ba_getaway.wav")
AddChatSound("get outta the way", "vo/npc/Barney/ba_getoutofway.wav")
AddChatSound("you're going down", "vo/npc/Barney/ba_goingdown.wav", true)
AddChatSound("grenade", "vo/npc/Barney/ba_grenade01.wav")
AddChatSound("here it comes!", "vo/npc/Barney/ba_hereitcomes.wav", true)
AddChatSound("hurry up", "vo/npc/Barney/ba_hurryup.wav")
AddChatSound("i'm with you buddy", "vo/npc/Barney/ba_imwithyou.wav", true)
AddChatSound("maniacal!", "vo/npc/Barney/ba_laugh01.wav", true)
AddChatSound("yeaheheah", "vo/npc/Barney/ba_laugh03.wav", true)
AddChatSound("let's do it", "vo/npc/Barney/ba_letsdoit.wav", true)
AddChatSound("look out!", "vo/npc/Barney/ba_lookout.wav", true)
AddChatSound("i haven't lost my touch", "vo/npc/Barney/ba_losttouch.wav", true)
AddChatSound("ohoh yeah", "vo/npc/Barney/ba_ohyeah.wav", true)
AddChatSound("soldiers!", "vo/npc/Barney/ba_soldiers.wav", true)
AddChatSound("turret!", "vo/npc/Barney/ba_turret.wav", true)
AddChatSound("uh oh here they come", "vo/npc/Barney/ba_uhohheretheycome.wav", true)
AddChatSound("i need to get patched up", "vo/npc/Barney/ba_wounded02.wav", true)
AddChatSound("i'm hurt pretty bad", "vo/npc/Barney/ba_wounded03.wav", true)
AddChatSound("i know you will", "vo/NovaProspekt/eli_iknow.wav")
AddChatSound("nevermind me save yourselves", "vo/NovaProspekt/eli_nevermindme01.wav", true)
AddChatSound("i'll see you there baby", "vo/NovaProspekt/eli_notime01.wav", true)
AddChatSound("so this is the combine portal it's smaller than i imagined", "vo/NovaProspekt/eli_thisisportal.wav", true)
AddChatSound("but where will you go?", "vo/NovaProspekt/eli_wherewillyougo01.wav", true)
AddChatSound("instinct1", "vo/Breencast/br_instinct01.wav", true)
AddChatSound("instinct2", "vo/Breencast/br_instinct03.wav", true)
AddChatSound("instinct3", "vo/Breencast/br_instinct08.wav", true)
AddChatSound("instinct4", "vo/Breencast/br_instinct09.wav", true)
AddChatSound("instinct5", "vo/Breencast/br_instinct12.wav", true)
AddChatSound("instinct6", "vo/Breencast/br_instinct14.wav", true)
AddChatSound("instinct7", "vo/Breencast/br_instinct15.wav", true)
AddChatSound("instinct8", "vo/Breencast/br_instinct16.wav", true)
AddChatSound("instinct9", "vo/Breencast/br_instinct17.wav", true)
AddChatSound("instinct10", "vo/Breencast/br_instinct18.wav", true)
AddChatSound("instinct11", "vo/Breencast/br_instinct19.wav", true)
AddChatSound("instinct12", "vo/Breencast/br_instinct20.wav", true)
AddChatSound("instinct13", "vo/Breencast/br_instinct21.wav", true)
AddChatSound("instinct14", "vo/Breencast/br_instinct22.wav", true)
AddChatSound("instinct15", "vo/Breencast/br_instinct23.wav", true)
AddChatSound("instinct16", "vo/Breencast/br_instinct25.wav", true)
AddChatSound("you have plunged humanity in to free fall", "vo/Breencast/br_tofreeman06.wav", true)
AddChatSound("even if you offered your surrunder now", "vo/Breencast/br_tofreeman07.wav", true)
AddChatSound("help ensure that humanity's trust in you is not misguided", "vo/Breencast/br_tofreeman10.wav", true)
AddChatSound("they're shelling us", "vo/canals/male01/stn6_shellingus.wav", true)
AddChatSound("incoming!", "vo/canals/male01/stn6_incoming.wav", true)
AddChatSound("you can park the boat it'll be safe here", "vo/canals/male01/gunboat_parkboat.wav", true)
AddChatSound("let's get a move on we gotta move out before they target us", "vo/canals/male01/gunboat_moveon.wav", true)
AddChatSound("you made it just in time we gotta clear outta here before we're discovered", "vo/canals/male01/gunboat_justintime.wav", true)
AddChatSound("we'd better hurry we gotta tear down this camp and get outta here", "vo/canals/male01/gunboat_hurry.wav", true)
AddChatSound("be careful now", "vo/canals/boxcar_becareful.wav", true)
AddChatSound("we really can't afford to get noticed", "vo/canals/boxcar_becareful_b.wav", true)
AddChatSound("better get going", "vo/canals/boxcar_go_nag02.wav", true)
AddChatSound("he'll help you if you let him", "vo/canals/boxcar_lethimhelp.wav", true)
AddChatSound("we're just a lookout for the underground railroad", "vo/canals/boxcar_lookout.wav", true)
AddChatSound("main station's right around the corner", "vo/canals/boxcar_lookout_b.wav", true)
AddChatSound("they'll get you started on the right foot", "vo/canals/boxcar_lookout_d.wav", true)
AddChatSound("guess those sirens are for you", "vo/canals/boxcar_sirens.wav", true)
AddChatSound("come on in i'll show you what you're up against", "vo/canals/gunboat_comein.wav", true)
AddChatSound("i think he's just finishing up now", "vo/canals/gunboat_finishingup.wav", true)
AddChatSound("come on get in here", "vo/canals/gunboat_getin.wav", true)
AddChatSound("here take a look at this", "vo/canals/gunboat_herelook.wav", true)
AddChatSound("be glad you're not the guy they're looking for", "vo/canals/matt_beglad.wav", true)
AddChatSound("poor bastard doesn't stand a chance", "vo/canals/matt_beglad_b.wav", true)
AddChatSound("sounds like they're calling in every cp unit in city 17", "vo/canals/matt_beglad_c.wav", true)
AddChatSound("that was a close call thanks for your help", "vo/canals/matt_closecall.wav", true)
AddChatSound("now they're flooding the areas up ahead with manhacks", "vo/canals/matt_flood.wav", true)
AddChatSound("you'd better get going before they sweep through here", "vo/canals/matt_flood_b.wav", true)
AddChatSound("you'd better get going now", "vo/canals/matt_go_nag01.wav", true)
AddChatSound("thanks but i'll be ok", "vo/canals/matt_go_nag02.wav", true)
AddChatSound("i've got to stay and help any stragglers", "vo/canals/matt_go_nag03.wav", true)
AddChatSound("you go on", "vo/canals/matt_go_nag05.wav", true)
AddChatSound("good luck out there", "vo/canals/matt_goodluck.wav", true)
AddChatSound("civil protection is on to us", "vo/canals/matt_tearinguprr.wav", true)
AddChatSound("we're tearing up the railroad covering our tracks", "vo/canals/matt_tearinguprr_a.wav", true)
AddChatSound("looks like you're gonna be the last one through", "vo/canals/matt_tearinguprr_b.wav", true)
AddChatSound("thanks for the help but you better get outta here", "vo/canals/matt_thanksbut.wav", true)
AddChatSound("oh shit too late", "vo/canals/matt_toolate.wav", true)
AddChatSound("you got here at a bad time", "vo/canals/shanty_badtime.wav", true)
AddChatSound("we got some ammo in those crates over there", "vo/canals/shanty_gotsomeammo.wav", true)
AddChatSound("we got word you were coming", "vo/canals/shanty_gotword.wav", true)
AddChatSound("help yourself to supplies and keep moving", "vo/canals/shanty_helpyourself.wav", true)
AddChatSound("did you realize your contract was open to the highest bidder?", "vo/Citadel/br_bidder_b.wav", true)
AddChatSound("that's all up to you my old friend", "vo/Citadel/br_gift_a.wav", true)
AddChatSound("will you give your child a chance her mother never had?", "vo/Citadel/br_gift_c.wav", true)
AddChatSound("what's this oh put it over there", "vo/Citadel/br_gravgun.wav", true)
AddChatSound("guards get in here", "vo/Citadel/br_guards.wav", true)
AddChatSound("you have my gratitude doctor", "vo/Citadel/br_guest_b.wav", true)
AddChatSound("and then you deliver yourself?", "vo/Citadel/br_guest_d.wav", true)
AddChatSound("i don't know what you can possibly hope to achieve", "vo/Citadel/br_mock05.wav", true)
AddChatSound("i warned you this was futile", "vo/Citadel/br_mock06.wav", true)
AddChatSound("i hope you said your farewells", "vo/Citadel/br_mock09.wav", true)
AddChatSound("if only you had harnessed your boundless energy for a useful purpose", "vo/Citadel/br_mock13.wav", true)
AddChatSound("i agree it's a total waste", "vo/Citadel/br_newleader_a.wav", true)
AddChatSound("this one has proven to be a fine pawn", "vo/Citadel/br_newleader_c.wav", true)
AddChatSound("i understand if you don't wish to discuss this in front of your friends", "vo/Citadel/br_nothingtosay_a.wav", true)
AddChatSound("i'll send them on their way and then we can talk openly", "vo/Citadel/br_nothingtosay_b.wav", true)
AddChatSound("impossible to describe with our limited vocabulary", "vo/Citadel/br_oheli09.wav", true)
AddChatSound("oh shit", "vo/Citadel/br_ohshit.wav", true)
AddChatSound("if you won't do the right thing for the good of all people", "vo/Citadel/br_playgame_b.wav", true)
AddChatSound("maybe you'll do it for one of them", "vo/Citadel/br_playgame_c.wav", true)
AddChatSound("thanks to you we have everything we need in that regard", "vo/Citadel/br_rabble_a.wav", true)
AddChatSound("you're more than qualified to finish his research yourself", "vo/Citadel/br_rabble_b.wav", true)
AddChatSound("if that's what it takes", "vo/Citadel/br_whatittakes.wav", true)
AddChatSound("you need me", "vo/Citadel/br_youneedme.wav", true)
AddChatSound("don't struggle honey", "vo/Citadel/eli_dontstruggle.wav", true)
AddChatSound("don't worry about me", "vo/Citadel/eli_dontworryboutme.wav", true)
AddChatSound("that's my girl", "vo/Citadel/eli_mygirl.wav", true)
AddChatSound("save them for what", "vo/Citadel/eli_save.wav", true)
AddChatSound("is it really that time again?", "vo/Citadel/gman_exit02.wav", true)
AddChatSound("i'm really not at liberty to say", "vo/Citadel/gman_exit08.wav", true)
AddChatSound("in the meantime", "vo/Citadel/gman_exit09.wav", true)
AddChatSound("this is where i get off", "vo/Citadel/gman_exit10.wav", true)
AddChatSound("they're looking for your car", "vo/coast/barn/male01/chatter.wav", true)
AddChatSound("here come the dropships", "vo/coast/barn/male01/crapships.wav", true)
AddChatSound("right along there and watch your step", "vo/coast/barn/male01/exit_watchstep.wav", true)
AddChatSound("get your car in the barn", "vo/coast/barn/male01/getcarinbarn.wav", true)
AddChatSound("get your car in the garage", "vo/coast/barn/male01/getcaringarage.wav", true)
AddChatSound("get off the road", "vo/coast/barn/male01/getoffroad01.wav", true)
AddChatSound("incoming dropship", "vo/coast/barn/male01/incomingdropship.wav", true)
AddChatSound("it's a gunship", "vo/coast/barn/male01/lite_gunship01.wav", true)
AddChatSound("gunship", "vo/coast/barn/male01/lite_gunship02.wav", true)
AddChatSound("park it there", "vo/coast/barn/male01/parkit.wav", true)
AddChatSound("you made it", "vo/coast/barn/male01/youmadeit.wav", true)
AddChatSound("you idiot walking on the sand brings antlions after you", "vo/coast/bugbait/sandy_youidiot.wav", true)
AddChatSound("you there", "vo/coast/bugbait/sandy_youthere.wav", true)
AddChatSound("stop where you are stay on the rocks", "vo/coast/bugbait/sandy_stop.wav", true)
AddChatSound("no! help!", "vo/coast/bugbait/sandy_help.wav", true)
AddChatSound("yeah good idea hold on a sec", "vo/coast/cardock/le_goodidea.wav", true)
AddChatSound("patch him up and get him to the back as soon as he's stable", "vo/coast/cardock/le_patchhim.wav", true)
AddChatSound("i'll radio ahead to let the next base know you're coming", "vo/coast/cardock/le_radio.wav", true)
AddChatSound("who's hurt?", "vo/coast/cardock/le_whohurt.wav", true)
AddChatSound("well that's that", "vo/coast/odessa/nlo_cub_thatsthat.wav", true)
AddChatSound("i couldn't have asked for a finer volunteer", "vo/coast/odessa/nlo_cub_volunteer.wav", true)
AddChatSound("you'll make it through if anyone can", "vo/coast/odessa/nlo_cub_youllmakeit.wav", true)
AddChatSound("good to know you", "vo/eli_lab/airlock_cit01.wav", true)
AddChatSound("you'd better get going", "vo/eli_lab/airlock_cit02.wav", true)
AddChatSound("awesome!", "vo/eli_lab/al_awesome.wav", true)
AddChatSound("alright good you keep right on it", "vo/eli_lab/eli_goodvort.wav", true)
AddChatSound("ughghgh", "vo/eli_lab/eli_handle_b.wav", true)
AddChatSound("ughhh", "vo/k_lab/ba_thingaway02.wav", true)
AddChatSound("feel free to look around", "vo/eli_lab/eli_lookaround.wav", true)
AddChatSound("dr. breen", "vo/eli_lab/eli_vilebiz01.wav", true)
AddChatSound("i can't look", "vo/k_lab/ba_cantlook.wav", true)
AddChatSound("careful", "vo/k_lab/ba_careful01.wav")
AddChatSound("be careful!", "vo/k_lab/ba_careful01.wav", true)
AddChatSound("forget about that thing", "vo/k_lab/ba_forgetthatthing.wav", true)
AddChatSound("get it off me", "vo/k_lab/ba_getitoff02.wav", true)
AddChatSound("get down outta sight", "vo/k_lab/ba_getoutofsight01.wav", true)
AddChatSound("i'll come find you", "vo/k_lab/ba_getoutofsight02.wav", true)
AddChatSound("guh", "vo/k_lab/ba_guh.wav", true)
AddChatSound("hey hey he's back", "vo/k_lab/ba_hesback01.wav", true)
AddChatSound("i'm getting him outta there", "vo/k_lab/ba_hesback02.wav", true)
AddChatSound("well is he here?", "vo/k_lab/ba_ishehere.wav", true)
AddChatSound("you mean it's working?", "vo/k_lab/ba_itsworking01.wav", true)
AddChatSound("for real this time?", "vo/k_lab/ba_itsworking02.wav", true)
AddChatSound("i still have nightmares about that cat", "vo/k_lab/ba_itsworking04.wav", true)
AddChatSound("i've gotta get back on my shift", "vo/k_lab/ba_myshift01.wav", true)
AddChatSound("but ok", "vo/k_lab/ba_myshift02.wav")
AddChatSound("yeah longer if we're lucky", "vo/k_lab/ba_longer.wav", true)
AddChatSound("and not a moment too soon", "vo/k_lab/ba_nottoosoon01.wav", true)
AddChatSound("that's what you said last time", "vo/k_lab/ba_saidlasttime.wav", true)
AddChatSound("i can tell your mit education really pays for itself", "vo/k_lab/ba_sarcastic03.wav", true)
AddChatSound("i thought you got rid of that pest", "vo/k_lab/ba_thatpest.wav", true)
AddChatSound("there he is", "vo/k_lab/ba_thereheis.wav", true)
AddChatSound("there you are", "vo/k_lab/ba_thereyouare.wav", true)
AddChatSound("here we go", "vo/k_lab/ba_thingaway01.wav", true)
AddChatSound("get that thing away from me", "vo/k_lab/ba_thingaway03.wav", true)
AddChatSound("what's the meaning of this?", "vo/k_lab/br_tele_02.wav", true)
AddChatSound("who are you?", "vo/k_lab/br_tele_03.wav")
AddChatSound("how did you get in here?", "vo/k_lab/br_tele_05.wav", true)
AddChatSound("see for yourself", "vo/k_lab/eli_seeforyourself.wav", true)
AddChatSound("shut it down shut it down", "vo/k_lab/eli_shutdown.wav", true)
AddChatSound("ahhhh", "vo/k_lab/kl_ahhhh.wav", true)
AddChatSound("there's a charger on the wall", "vo/k_lab/kl_charger01.wav", true)
AddChatSound("dear me", "vo/k_lab/kl_dearme.wav", true)
AddChatSound("well did it work?", "vo/k_lab/kl_diditwork.wav", true)
AddChatSound("excellent!", "vo/k_lab/kl_excellent.wav", true)
AddChatSound("right you are", "vo/k_lab/kl_fewmoments01.wav", true)
AddChatSound("speak to you again in a few moments", "vo/k_lab/kl_fewmoments02.wav", true)
AddChatSound("oh fiddlesticks what now", "vo/k_lab/kl_fiddlesticks.wav", true)
AddChatSound("final sequence", "vo/k_lab/kl_finalsequence02.wav", true)
AddChatSound("you must get out of here", "vo/k_lab/kl_getoutrun02.wav", true)
AddChatSound("run!", "vo/k_lab/kl_getoutrun03.wav", true)
AddChatSound("here my pet", "vo/k_lab/kl_heremypet01.wav", true)
AddChatSound("no not up there", "vo/k_lab/kl_heremypet02.wav", true)
AddChatSound("interference!", "vo/k_lab/kl_interference.wav", true)
AddChatSound("lamarr", "vo/k_lab/kl_hedyno01.wav", true)
AddChatSound("heady", "vo/k_lab/kl_hedyno02.wav", true)
AddChatSound("is lamarr with him?", "vo/k_lab/kl_islamarr.wav", true)
AddChatSound("lamarr there you are", "vo/k_lab/kl_lamarr.wav", true)
AddChatSound("careful lamarr those are quite fragile", "vo/k_lab/kl_nocareful.wav", true)
AddChatSound("conditions could hardly be more ideal", "vo/k_lab/kl_moduli02.wav", true)
AddChatSound("my goodness", "vo/k_lab/kl_mygoodness01.wav", true)
AddChatSound("it really is you isn't it?", "vo/k_lab/kl_mygoodness03.wav", true)
AddChatSound("your talents surpass your loveliness", "vo/k_lab/kl_nonsense.wav", true)
AddChatSound("oh dear", "vo/k_lab/kl_ohdear.wav", true)
AddChatSound("indeed it is", "vo/k_lab/kl_packing01.wav", true)
AddChatSound("slip in to your suit now", "vo/k_lab/kl_slipin02.wav", true)
AddChatSound("i'm eager to see if your old suit still fits", "vo/k_lab/kl_suitfits02.wav", true)
AddChatSound("then where is he?", "vo/k_lab/kl_thenwhere.wav", true)
AddChatSound("what is it?", "vo/k_lab/kl_whatisit.wav")
AddChatSound("i wish i knew!", "vo/k_lab/kl_wishiknew.wav", true)
AddChatSound("go on get going", "vo/k_lab2/ba_getgoing.wav", true)
AddChatSound("well man that's good news", "vo/k_lab2/ba_goodnews.wav", true)
AddChatSound("i almost gave you guys up for lost", "vo/k_lab2/ba_goodnews_b.wav", true)
AddChatSound("i'll take all the help i can get", "vo/k_lab2/ba_goodnews_c.wav", true)
AddChatSound("aw crap incoming!", "vo/k_lab2/ba_incoming.wav", true)
AddChatSound("so there you see?", "vo/k_lab2/kl_notallhopeless.wav", true)
AddChatSound("it's not all hopeless", "vo/k_lab2/kl_notallhopeless_b.wav", true)
AddChatSound("there's only one heady", "vo/k_lab2/kl_onehedy.wav", true)
AddChatSound("fascinating!", "vo/k_lab2/kl_slowteleport01.wav", true)
AddChatSound("aim for the head", "vo/ravenholm/aimforthehead.wav", true)
AddChatSound("guard yourself well", "vo/ravenholm/bucket_guardwell.wav", true)
AddChatSound("there you are at last", "vo/ravenholm/bucket_thereyouare.wav", true)
AddChatSound("better than better", "vo/ravenholm/cartrap_better.wav", true)
AddChatSound("yes come to me come", "vo/ravenholm/engage01.wav", true)
AddChatSound("come!", "vo/ravenholm/engage02.wav", "vo/ravenholm/engage03.wav", true)
AddChatSound("i will end your torment", "vo/ravenholm/engage04.wav", true)
AddChatSound("let me end your torment", "vo/ravenholm/engage05.wav", true)
AddChatSound("yes my children it is i", "vo/ravenholm/engage06.wav", true)
AddChatSound("come to the light i carry come", "vo/ravenholm/engage07.wav", true)
AddChatSound("it is not me you want but the light that shines through me", "vo/ravenholm/engage08.wav", true)
AddChatSound("come to the light", "vo/ravenholm/engage09.wav", true)
AddChatSound("go quickly", "vo/ravenholm/exit_goquickly.wav", true)
AddChatSound("hurry while i hold the gate", "vo/ravenholm/exit_hurry.wav", true)
AddChatSound("flee brother", "vo/ravenholm/exit_nag01.wav", true)
AddChatSound("onward to the mines", "vo/ravenholm/exit_nag02.wav", true)
AddChatSound("look out brother behind you", "vo/ravenholm/firetrap_lookout.wav", true)
AddChatSound("well done brother", "vo/ravenholm/firetrap_welldone.wav", true)
AddChatSound("stay close to me brother", "vo/ravenholm/grave_stayclose.wav", true)
AddChatSound("out of my way", "vo/ravenholm/monk_blocked01.wav", true)
AddChatSound("look out", "vo/ravenholm/monk_blocked02.wav")
AddChatSound("stand aside brother", "vo/ravenholm/monk_blocked03.wav", true)
AddChatSound("cover me brother", "vo/ravenholm/monk_coverme01.wav", true)
AddChatSound("your assistance brother", "vo/ravenholm/monk_coverme02.wav", true)
AddChatSound("over here brother", "vo/ravenholm/monk_coverme03.wav", true)
AddChatSound("to me brother", "vo/ravenholm/monk_coverme04.wav", true)
AddChatSound("i require your assistance brother", "vo/ravenholm/monk_coverme05.wav", true)
AddChatSound("where art thou brother", "vo/ravenholm/monk_coverme07.wav", true)
AddChatSound("beware!", "vo/ravenholm/monk_danger02.wav", true)
AddChatSound("careful brother", "vo/ravenholm/monk_danger03.wav", true)
AddChatSound("i am outnumbered", "vo/ravenholm/monk_helpme01.wav", true)
AddChatSound("help me brother", "vo/ravenholm/monk_helpme02.wav", true)
AddChatSound("i cannot fight them all alone", "vo/ravenholm/monk_helpme03.wav", true)
AddChatSound("lend a hand brother", "vo/ravenholm/monk_helpme04.wav", true)
AddChatSound("i need help brother", "vo/ravenholm/monk_helpme05.wav", true)
AddChatSound("rest my child", "vo/ravenholm/monk_kill03.wav", true)
AddChatSound("i think no worse of thee", "vo/ravenholm/monk_kill04.wav", true)
AddChatSound("may the light of lights be with you", "vo/ravenholm/monk_kill05.wav", true)
AddChatSound("you meant no harm", "vo/ravenholm/monk_kill06.wav", true)
AddChatSound("be free my child", "vo/ravenholm/monk_kill09.wav", true)
AddChatSound("the grave holds nothing worse for you", "vo/ravenholm/monk_kill10.wav", true)
AddChatSound("i remember your true face", "vo/ravenholm/monk_kill11.wav", true)
AddChatSound("so again i am alone", "vo/ravenholm/monk_mourn03.wav", true)
AddChatSound("my advice to you is aim for the head", "vo/ravenholm/shotgun_advice.wav", true)
AddChatSound("here i have a more suitable gun for you", "vo/ravenholm/shotgun_bettergun.wav", true)
AddChatSound("catch!", "vo/ravenholm/shotgun_catch.wav", true)
AddChatSound("come closer", "vo/ravenholm/shotgun_closer.wav", true)
AddChatSound("hush", "vo/ravenholm/shotgun_hush.wav")
AddChatSound("good now keep it close", "vo/ravenholm/shotgun_keepitclose.wav", true)
AddChatSound("they come", "vo/ravenholm/shotgun_theycome.wav", true)
AddChatSound("if you can hold them off i'm almost done here", "vo/Streetwar/tunnel/male01/c17_06_det02.wav", true)
AddChatSound("stand back it's gonna blow", "vo/Streetwar/tunnel/male01/c17_06_det04.wav", true)
AddChatSound("hey it's me open the door", "vo/Streetwar/tunnel/male01/c17_06_password01.wav", true)
AddChatSound("what's the password?", "vo/Streetwar/tunnel/male01/c17_06_password02.wav", true)
AddChatSound("password!", "vo/Streetwar/tunnel/male01/c17_06_password03.wav", true)
AddChatSound("come on in", "vo/Streetwar/tunnel/male01/c17_06_password04.wav", true)
AddChatSound("ok come across", "vo/Streetwar/tunnel/male01/c17_06_plank01.wav", true)
AddChatSound("that damn thing haunts me", "vo/Streetwar/sniper/ba_hauntsme.wav", true)
AddChatSound("did you hear a cat just now?", "vo/Streetwar/sniper/ba_hearcat.wav", true)
AddChatSound("hey come on", "vo/Streetwar/sniper/ba_heycomeon.wav", true)
AddChatSound("let's get going", "vo/Streetwar/sniper/ba_letsgetgoing.wav", true)
AddChatSound("heeelp", "vo/Streetwar/sniper/male01/c17_09_help01.wav", true)
AddChatSound("help me!", "vo/Streetwar/sniper/male01/c17_09_help02.wav", true)
AddChatSound("is somebody up there?", "vo/Streetwar/sniper/male01/c17_09_help03.wav", true)
AddChatSound("damnit all", "vo/Streetwar/rubble/ba_damnitall.wav", true)
AddChatSound("hey help me out here", "vo/Streetwar/rubble/ba_helpmeout.wav", true)
AddChatSound("well i'll be damned", "vo/Streetwar/rubble/ba_illbedamned.wav", true)
AddChatSound("and if you see dr. breen tell him i said fuck you", "vo/Streetwar/rubble/ba_tellbreen.wav", true)
AddChatSound("done!", "vo/Streetwar/nexus/ba_done.wav", true)
AddChatSound("great i'll open this up", "vo/Streetwar/nexus/ba_illopenthis.wav", true)
AddChatSound("so much for stealth we've been spotted", "vo/Streetwar/nexus/ba_spotted.wav", true)
AddChatSound("we're surrounded", "vo/Streetwar/nexus/ba_surrounded.wav", true)
AddChatSound("then let's go", "vo/Streetwar/nexus/ba_thenletsgo.wav", true)
AddChatSound("uh oh dropships", "vo/Streetwar/nexus/ba_uhohdropships.wav", true)
AddChatSound("hey let us outta here", "vo/Streetwar/nexus/male01/c17_10_letusout.wav", true)
AddChatSound("let us thru!", "vo/Streetwar/barricade/male01/c17_05_letusthru.wav", true)
AddChatSound("let us through!", "vo/Streetwar/barricade/male01/c17_05_letusthru.wav", true)
AddChatSound("open the gate!", "vo/Streetwar/barricade/male01/c17_05_opengate.wav", true)
AddChatSound("how dare you even mention her", "vo/Citadel/al_dienow_b.wav", true)
AddChatSound("alyx my dear you have your mother's eyes but your father's stubborn nature", "vo/Citadel/br_stubborn.wav", true)
AddChatSound("it isn't necessary", "vo/Citadel/mo_necessary.wav", true)

Chatbox = vgui.Create("deathrun.vgui.chatbox")
Chatbox:Close()

function Cure:CreateChatbox()
	Chatbox = vgui.Create("deathrun.vgui.chatbox")
	Chatbox:AddTab("General chat", "icon16/keyboard.png")
	Chatbox:AddTab("Admin chat", "icon16/shield.png")
	Chatbox.Think = function()
		for k, v in pairs(MessageHolder.Data) do
			if (Chatbox:IsVisible()) then
				v.Alpha = 255
			end
		end
	end

	Chatbox:MakePopup()

	return Chatbox
end

function Cure:PlayerBindPress( ply, bind, pressed )
    if pressed and string.find( bind, "messagemode" ) then
    	if (Chatbox) then
    		if not (type(Chatbox) == "table") then
    			Chatbox:Remove()
    		end 
    	end

        Chatbox = Cure:CreateChatbox()

        Chatbox.TextEntry:SetText("")
        Chatbox.TextEntry:RequestFocus()

        MessageHolder:SetParent(Chatbox)
        return true
    end
end

function Cure:FinishChat()
	return true
end

function Cure:StartChat()
	return true
end

-- Add a message
function Cure.AddChatMessage(player, message, icon)
	-- Wait till chatbox is valid
	if not (Chatbox) or not (Chatbox:IsValid()) then return end

	local pnl = (#MessageHolder.Data + 1)

	-- Create
	MessageHolder.Data[pnl] = vgui.Create("deathrun.vgui.chatmessage")
	-- Message
	MessageHolder.Data[pnl]:SetText(message)
	-- Player
	MessageHolder.Data[pnl]:SetPlayer(player)

	-- Icon
	if (icon) then
		MessageHolder.Data[pnl]:SetIcon(icon)
	end

	-- Pos
	if (pnl == 1) then
		MessageHolder.Data[pnl]:SetPos(0, 0)
	else
		MessageHolder.Data[pnl-1]:PerformLayout()
		
		local x, y = MessageHolder.Data[pnl-1]:GetPos()
		local w, h = MessageHolder.Data[pnl-1]:GetSize()

		MessageHolder.Data[pnl]:SetPos(0, y + h + 1)
	end

	-- Add
	MessageHolder:Add(MessageHolder.Data[pnl])

	-- Scroll
	MessageHolder:ScrollToChild(MessageHolder.Data[pnl])

	-- Console
	MsgN((player and player:Name()..": " or "")..message)
end

function chat.AddText(...)
	local args = {...}
	local str = ""
	local usingcolor = false

	for k, v in pairs(args) do
		print(v)
		if (type(v) == "table") then
			str = str..Format("<color=%s, %s, %s>", v.r, v.g, v.b)
			usingcolor = true
		elseif (usingcolor) then
			if (type(v) == "string") then
				str = str..""..tostring(v).."</color>"
				usingcolor = false
			end
		else
			str = str..""..tostring(v)
		end
	end

	Cure.AddChatMessage(nil, str, Material("icon16/shield.png"))
end

function OnPlayerChat( ply, strText, bTeamOnly, bPlayerIsDead )
	-- Chatsounds
	if not ply.LastTrigger then
		ply.LastTrigger = 0
	end

	-- Console valid stuff
	if not (ply:IsValid()) then
		Cure.AddChatMessage(nil, "Console: "..strText, Material("icon16/application_xp_terminal.png"))
	else
		Cure.AddChatMessage(ply, strText)
	end

	-- Sounds
	for k, v in pairs( chatsounds ) do
		if (v.trigger == string.lower(strText) and ply:IsValid() and ply.LastTrigger < CurTime()) then
			surface.PlaySound(v.sound[1])
			ply.LastTrigger = CurTime() + 3
		end
	end
	
	-- Idk
	return true
end
hook.Add( "OnPlayerChat", "ChatBox.HandlePlayerChat", OnPlayerChat )

-- Chatmessages
net.Receive("cure.chatprint", function()
	-- Cache
	local text = net.ReadString()
	local icon = (Material(net.ReadString()) or Cure.Config.pIcons.world)

	-- Add
	Cure.AddChatMessage(nil, text, icon)
end)